pull_request_rules:
  - name: Automatically merge Public suffix list pull requests
    conditions:
      - author=github-actions
      - title=Update public suffix list
    actions:
      merge:
        method: squash
