name: E2E Tests

# Forked from https://github.com/fabric8io/kubernetes-client/blob/56a6c2c4f336cc6f64c19029a55c2d3d0289344f/.github/workflows/e2e-chaos-tests.yml

on:
  push:
    branches:
      - main
    tags-ignore:
      # The release versions will be verified by 'publish-release.yml'
      - armeria-*
  pull_request:

concurrency:
  group: ci-e2e-chaos-tests-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CHAOS_MESH_VERSION: 2.6.2
  KUBERNETES_VERSION: v1.25.0
  MINIKUBE_VERSION: v1.32.0

jobs:
  chaos-tests:
    name: Kubernetes Chaos Test
    runs-on: ubuntu-latest
    timeout-minutes: 120
    if: github.repository == 'line/armeria'
    steps:
      - uses: actions/checkout@v4

      - id: setup-jdk-19
        name: Setup Java 19
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 19

      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.9.0
        with:
          minikube version: ${{ env.MINIKUBE_VERSION }}
          kubernetes version: ${{ env.KUBERNETES_VERSION }}
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Kubectl # Chaos-Mesh setup requires a functional kubectl version for all cluster versiones
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBERNETES_VERSION }}

      - name: Install Chaos Mesh
        run: |
          curl -sSL https://mirrors.chaos-mesh.org/v${CHAOS_MESH_VERSION}/install.sh | bash
          kubectl wait --for=condition=Ready pods --all-namespaces --all --timeout=600s

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Chaos Tests - network-delay.yaml
        env:
          CHAOS_TEST: network-delay.yaml
        run: |
          ./gradlew --no-daemon --stacktrace :it:kubernetes-chaos-tests:test
        shell: bash

      - name: Run Chaos Tests - network-loss.yaml
        env:
          CHAOS_TEST: network-loss.yaml
        run: |
          ./gradlew --no-daemon --stacktrace :it:kubernetes-chaos-tests:test
        shell: bash

      - name: Run Chaos Tests - network-duplication.yaml
        env:
          CHAOS_TEST: network-duplication.yaml
        run: |
          ./gradlew --no-daemon --stacktrace :it:kubernetes-chaos-tests:test
        shell: bash
