name: Upload Gradle build scans to ge.armeria.dev

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  LC_ALL: "en_US.UTF-8"
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  ACTIONS_STEP_DEBUG: true
  GH_TOKEN: ${{ github.token }}
  GH_DEBUG: true
  RUN_ID: ${{ github.event.workflow_run.id }}

jobs:
  upload-gradle-build-scan:
    name: Upload Gradle build scans
    # TODO(ikhoon): Uncomment this after testing
#    if: github.repository == 'line/armeria'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: ""
          run_id: ${{ env.RUN_ID }}
          name: build-scan.*
          name_is_regexp: true
          path: build/build-scans
          check_artifacts: true
          search_artifacts: true

      # TODO(ikhoon): Remove '|| true' in the Gradle command when a build scan with JDK 8 can be published.
      # https://github.com/ikhoon/armeria/actions/runs/5771371947/job/15645266819#step:5:261
      - id: upload-build-scans
        name: Upload build scans
        run: |
          DOWNLOAD_DIR="build/build-scans/"
          BUILD_SCAN_DIR="${HOME}/.gradle/build-scan-data"
          BUILD_SCANS=""
          echo "## Build Scans®" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          mkdir -p $BUILD_SCAN_DIR
          for SCAN in $(ls $DOWNLOAD_DIR) ; do
            rm -rf $BUILD_SCAN_DIR
            cp -r "${DOWNLOAD_DIR}${SCAN}/" $BUILD_SCAN_DIR
            find $BUILD_SCAN_DIR
            echo "📤 Uploading build scan: ${SCAN} ..."
            ./gradlew --no-daemon --stacktrace buildScanPublishPrevious || true
            echo "✅ Published build scan: ${SCAN}"
            BUILD_SCANS="${SCAN} $(cat build/build-scan-url.txt)"$'\n'"${BUILD_SCANS}"
            echo "- [${SCAN}]($(cat build/build-scan-url.txt))" >> $GITHUB_STEP_SUMMARY
          done
          echo "BUILD_SCANS=${BUILD_SCANS}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - id: create-or-update-comment
        name: Create or update comment
        working-directory: .github/actions
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install
          npm run comment-build-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_SCANS: ${{ steps.upload-build-scans.outputs.BUILD_SCANS }}
          SHA: ${{ github.sha }}
#          RUN_ID: ${{ steps.get-run-id.outputs.CHECK_RUN_ID }}
