name: Publish artifacts to Maven Central repository

on:
  push:
    tags:
      - armeria-*

jobs:
  publish:
    name: Publish artifacts
    # TODO(ikhoon): Fix me
    if: github.repository == 'ikhoon/armeria'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-jdk-16
        name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Restore the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
          restore-keys: |
            build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
            build-${{ matrix.java }}-${{ runner.os }}-

      - name: Publish and close repository
        run: |
          ./gradlew --no-daemon --stacktrace --debug --console=plain --max-workers=1 publish \
          -PossrhUsername=${{ secrets.OSSRH_USER_NAME }} \
          -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} \
          -Psigning.keyId=${{ secrets.GPG_KEY_ID }} \
          -Psigning.password=${{ secrets.GPG_PASSWORD }} \
          -Psigning.gpgPrivateKey=${{ secrets.GPG_PRIVATE_KEY }}

      - name: Clean up Gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
        shell: bash
