name: Update Public Suffix List
on:
  schedule:
    # - cron: '0 10 * * *'
    - cron: '* * * * *'

jobs:
  update-psl:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - id: setup-jdk-15
        name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Restore Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists
            ~/.gradle/caches/jars-3
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/package-lists
            ~/.gradle/caches/embedded-consul
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace :core:publicSuffixes

      - name: Push updated PSL
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Public Suffix List
          file_pattern: core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
          # TODO(ikhoon): Use real GitHub account
          commit_user_name: Armeria GitHub Actions Bot
          commit_user_email: armeria@armeria.dev
          commit_author: Armeria Bot <armeria@armeria.dev>

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock || true
          rm -f ~/.gradle/caches/modules-2/gc.properties || true
        shell: bash
