name: Release a new Armeria version
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string
      next_version:
        description: 'Next Version'
        required: true
        type: string

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  tag-new-version:
    # TODO(ikhoon): Revert
    if: github.repository == 'ikhoon/armeria'
    runs-on: ubuntu-latest

    steps:
      - name: Validate inputs
        run: |
          if [[ ! "${{ inputs.release_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: 'release_version' should be in SemVer format."
            exit 1
          fi
          
          if [[ ! "${{ inputs.next_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: 'next_version' should be in SemVer format."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Correct remote url for release
        # TODO(ikhoon): Revert
        run: |
          git remote set-url origin https://github.com/ikhoon/armeria.git
        shell: bash

      - id: setup-jdk-19
        name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Bump up version
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 release \
          -PreleaseVersion=${{ inputs.release_version }} \
          -PnextVersion=${{ inputs.next_version }}
        shell: bash
